myproject/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^test/$', views.test),
    url(r'^index/$', views.index, name="index"),
    url(r'^detail/(?P<id>\d+)$', views.detail, name="detail"),
    url(r'^edit/(?P<id>\d+)$', views.edit, name="edit"),
    url(r'^save$', views.save, name="save"),
]

myproject/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include("myapp.urls", namespace="myapp")),
]

myproject/myapp/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    addtime = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

myproject/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models


# Create your views here.
def test(request):
    return HttpResponse("This is test")


def index(request):
    # article = models.Article.objects.get(pk=1)
    articles = models.Article.objects.all()
    return render(request, 'myapp/index.html', {"articles": articles})


def detail(request, id):
    article = models.Article.objects.get(pk=id)
    return render(request, 'myapp/detail.html', {"article": article})


def edit(request, id):
    if str(id) == "0":
        return render(request, 'myapp/edit.html')
    else:
        article = models.Article.objects.get(pk=id)
        return render(request, 'myapp/edit.html', {"article": article})


def save(request):
    id = request.POST.get("id", "0")
    title = request.POST.get("title", "title_default")
    content = request.POST.get("content", "content_default")
    if id == '0':
        models.Article.objects.create(title=title, content=content)
        # articles = models.Article.objects.all()
        # return render(request, 'myapp/index.html', {"articles": articles})
    else:
        article = models.Article.objects.get(pk=id)
        article.title = title
        article.content = content
        article.save()
        # return render(request, 'myapp/detail.html', {"article": article})
    articles = models.Article.objects.all()
    return render(request, 'myapp/index.html', {"articles": articles})

myproject/myapp/templates/myapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Detail</title>
</head>
<body>
<h1><a href="">{{article.title}}</a></h1>
<div>
    <p>{{article.content}}</p>
</div>
<div><a href="{% url 'myapp:edit' article.id %}">修改文章</a></div>
</ul>
</body>
</html>

myproject/myapp/templates/myapp/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Edit</title>
</head>
<body>

<div>
    <form action="{% url 'myapp:save' %}" method="post">
        {% csrf_token %}
        <div><input type="hidden" name="id" value="{{article.id | default:0}}"/></div>
        <div><input type="text" name="title" value="{{article.title | default:''}}"/></div>
        <div><input type="text" name="content" value="{{article.content | default:''}}"/></div>
        <div><input type="submit" name="提交"/></div>
    </form>
</div>

</ul>
</body>
</html>

myproject/myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Index</title>
</head>
<body>
<h1><a href="{% url 'myapp:edit' 0 %}">新文章</a></h1>
<ul>
    {% for article in articles %}
    <li><a href="{% url 'myapp:detail' article.id %}">{{article.title}}</a></li>
    {% endfor %}
</ul>
</body>
</html>